# Don't print a new line at the start of the prompt.
add_newline = false
# Don't use a dual line setup.
[line_break]
disabled = true
# Remove cmd timing of commands.
[cmd_duration]
disabled = true
# Things to add before the commands.
[character]
format = "[❯](bold red)[❯](bold yellow)[❯ ](bold green)"
# Setting Github icon.
[git_branch]
symbol = "  "
format = "[$symbol$branch]($style) "
# Setting description.
[directory]
format = "[  ](bold green) [$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
read_only_style = "bold red"
truncate_to_repo = false
# Language support.
[java]
symbol = "  "
format = "[${symbol}(${version} )](bold blue)"

[python]
symbol = "  "
format = "[${symbol}${pyenv_prefix}(${version} )](bold blue)"
